version: '3'

services:
  tech.task:
    image: tech.task
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=8080
    ports:
      - 8080:8080
    environment:
      - PORT